import type { Db } from './types'
import { addDays } from './utils'

/**
 * Deterministic dummy data for the Night Crawl partnerships demo.
 * Dates are generated relative to `todayIso` so the dashboard always
 * shows a mix of overdue / due-today / upcoming follow-ups.
 */
export function seedNightCrawl(todayIso: string): Db {
  const s = (offset: number) => addDays(todayIso, offset)

  const parceiros: Db['parceiros'] = [
    {
      id: 'p1',
      nome: 'Marina Alves',
      handle: '@marinapelasp',
      tipo: 'Instagram',
      contato: '+55 11 98812-4471',
      contatos: ['+55 11 98812-4471'],
      cidade: 'São Paulo',
      idioma: 'PT',
      links: ['@marinapelasp'],
      pedido: 'Comissão de 20% + 2 cortesias',
      origem: 'Busca por hashtag',
      notas: 'Forte com o público da Vila Madalena.',
      responsavel: 'Eu',
      codigo: 'MARINA15',
      desconto: '15',
      comissao: '20',
      etapa: 'Negociando',
      proximo: s(-3),
      registros: [
        { data: s(-14), tipo: 'DM enviada', texto: 'Abri falando do roteiro da Vila Madalena.' },
        { data: s(-11), tipo: 'Respondeu', texto: 'Interessada, perguntou como funciona a comissão.' },
        { data: s(-6), tipo: 'Proposta enviada', texto: '20% de comissão + duas cortesias.' },
      ],
    },
    {
      id: 'p2',
      nome: 'Guia da Noite SP',
      handle: 'guiadanoitesp.com.br',
      tipo: 'Site de guia',
      contato: 'contato@guiadanoitesp.com.br',
      contatos: ['contato@guiadanoitesp.com.br'],
      cidade: 'São Paulo',
      idioma: 'PT',
      links: ['guiadanoitesp.com.br'],
      pedido: 'R$ 450/mês + comissão',
      origem: 'Google',
      notas: 'Querem as fotos de agosto antes de publicar.',
      responsavel: 'Ana',
      codigo: 'GUIANOITE',
      desconto: '10',
      comissao: '15',
      etapa: 'Fechado',
      proximo: s(-1),
      registros: [
        { data: s(-20), tipo: 'E-mail enviado', texto: 'Perguntei sobre listagem de parceiro.' },
        { data: s(-4), tipo: 'Ligação / reunião', texto: 'Fechamos R$ 450/mês por 6 meses.' },
      ],
    },
    {
      id: 'p3',
      nome: 'Tom Whitfield',
      handle: '@backpackwithtom',
      tipo: 'YouTube',
      contato: 'tom@backpackwith.com',
      contatos: ['tom@backpackwith.com'],
      cidade: 'São Paulo',
      idioma: 'EN',
      links: ['@backpackwithtom'],
      pedido: 'Crawl grátis para ele + editor',
      origem: 'Indicação de hostel',
      notas: 'Na cidade de 22 a 26 de agosto.',
      responsavel: 'Eu',
      codigo: 'TOM15',
      desconto: '15',
      comissao: '20',
      etapa: 'Respondeu',
      proximo: s(0),
      registros: [
        { data: s(-8), tipo: 'E-mail enviado', texto: 'Ofereci o trecho da Augusta.' },
        { data: s(-2), tipo: 'Respondeu', texto: 'Pediu datas e tamanho do grupo.' },
      ],
    },
    {
      id: 'p4',
      nome: 'Ô de Casa Hostel',
      handle: 'odecasahostel.com',
      tipo: 'Hostel / hotel',
      contato: 'Rita — recepção',
      contatos: ['Rita — recepção'],
      cidade: 'São Paulo',
      idioma: 'PT',
      links: ['odecasahostel.com'],
      pedido: 'R$ 15 por hóspede',
      origem: 'Visita presencial',
      notas: 'Manda de 8 a 12 hóspedes por semana no verão.',
      responsavel: 'Bruno',
      codigo: 'ODECASA',
      desconto: '15',
      comissao: '25',
      etapa: 'No ar',
      proximo: s(12),
      registros: [
        { data: s(-40), tipo: 'Ligação / reunião', texto: 'Mês de teste combinado com a Rita.' },
        { data: s(-9), tipo: 'Post publicado', texto: 'Cartaz na recepção + story.' },
      ],
    },
    {
      id: 'p5',
      nome: 'Sofia & Duda',
      handle: '@duasnanoitesp',
      tipo: 'TikTok',
      contato: 'Só DM',
      contatos: ['Só DM'],
      cidade: 'São Paulo',
      idioma: 'PT',
      links: ['@duasnanoitesp'],
      pedido: '',
      origem: 'TikTok — tag vida noturna SP',
      notas: 'Engajamento altíssimo.',
      responsavel: 'Ana',
      codigo: 'DUAS15',
      desconto: '15',
      comissao: '20',
      etapa: 'Contactado',
      proximo: s(1),
      registros: [{ data: s(-3), tipo: 'DM enviada', texto: 'Primeira abordagem, sem resposta.' }],
    },
    {
      id: 'p6',
      nome: 'Bar Tijuana',
      handle: 'bartijuana.com.br',
      tipo: 'Bar / casa noturna',
      contato: 'Nuno — dono',
      contatos: ['Nuno — dono'],
      cidade: 'São Paulo',
      idioma: 'PT',
      links: ['bartijuana.com.br'],
      pedido: '25 pessoas garantidas nas quartas',
      origem: 'Já está no roteiro',
      notas: 'Quer acordo por escrito.',
      responsavel: 'Eu',
      codigo: 'TIJUANA',
      desconto: '15',
      comissao: '20',
      etapa: 'Fechado',
      proximo: s(4),
      registros: [{ data: s(-5), tipo: 'Proposta enviada', texto: 'Minuta enviada para as quartas.' }],
    },
    {
      id: 'p7',
      nome: 'Intercâmbio SP',
      handle: '@intercambiosp',
      tipo: 'Agência de eventos',
      contato: 'parcerias@intercambiosp.com',
      contatos: ['parcerias@intercambiosp.com'],
      cidade: 'São Paulo',
      idioma: 'PT',
      links: ['@intercambiosp'],
      pedido: 'Comissão por venda',
      origem: 'E-mail frio',
      notas: '',
      responsavel: 'Bruno',
      codigo: 'INTERSP',
      desconto: '15',
      comissao: '20',
      etapa: 'Contactado',
      proximo: s(3),
      registros: [{ data: s(-7), tipo: 'E-mail enviado', texto: 'Proposta de afiliado 20%.' }],
    },
    {
      id: 'p8',
      nome: 'Viator BR',
      handle: 'viator.com',
      tipo: 'Operadora / OTA',
      contato: 'supplier@viator.com',
      contatos: ['supplier@viator.com'],
      cidade: 'São Paulo',
      idioma: 'EN',
      links: ['viator.com'],
      pedido: '20–25% de comissão',
      origem: 'Cadastro de fornecedor',
      notas: 'Precisa de CNPJ ativo e seguro.',
      responsavel: 'Ana',
      codigo: 'VIATOR',
      desconto: '15',
      comissao: '20',
      etapa: 'Novo',
      proximo: s(6),
      registros: [],
    },
  ]

  const vendas: Db['vendas'] = [
    { id: 'v1', data: s(-8), parceiroId: 'p4', cliente: 'Lucas (despedida)', pessoas: '11', valor: '1320', pago: true },
    { id: 'v2', data: s(-5), parceiroId: 'p2', cliente: 'Hannah + 2', pessoas: '3', valor: '360', pago: false },
    { id: 'v3', data: s(-2), parceiroId: 'p4', cliente: 'Grupo argentino', pessoas: '6', valor: '720', pago: false },
    { id: 'v4', data: s(-1), parceiroId: '', cliente: 'Direto no Instagram', pessoas: '2', valor: '240', pago: false },
  ]

  const clientes: Db['clientes'] = [
    { id: 'c1', nome: 'Lucas Prado', contato: '+55 11 99126-3388', pais: 'BR', tipo: 'Despedida de solteiro', origem: 'p:p4', data: s(-8), notas: '' },
    { id: 'c2', nome: 'Hannah Meyer', contato: '+49 151 2233 991', pais: 'DE', tipo: 'Grupo de turistas', origem: 'p:p2', data: s(-5), notas: '' },
    { id: 'c3', nome: 'Camila Ferrari', contato: '+55 11 97744-1020', pais: 'BR', tipo: 'Local / recorrente', origem: 'direto', data: s(-1), notas: 'Já veio duas vezes.' },
  ]

  const sites: Db['sites'] = [
    { id: 'si1', nome: 'TripAdvisor', url: 'https://tripadvisor.com', status: 'Precisa de avaliações', responsavel: 'Eu', proximaAcao: 'Pedir 5 avaliações aos grupos desta semana' },
    { id: 'si2', nome: 'Reddit r/saopaulo', url: 'https://reddit.com/r/saopaulo', status: 'Não estamos', responsavel: 'Bruno', proximaAcao: 'Responder threads de turistas sem vender de cara' },
    { id: 'si3', nome: 'GetYourGuide', url: 'https://getyourguide.com', status: 'Cadastro enviado', responsavel: 'Ana', proximaAcao: 'Cobrar aprovação do cadastro' },
    { id: 'si4', nome: 'Google Maps', url: 'https://maps.google.com', status: 'Ativo', responsavel: 'Eu', proximaAcao: 'Subir fotos novas todo mês' },
  ]

  const modelos: Db['modelos'] = [
    {
      id: 'm1',
      nome: 'Primeira abordagem',
      texto:
        'Oi {primeiro_nome}, tudo bem? Aqui é {meu_nome}, do {crawl} — a gente faz pub crawl em {cidade} para turistas e para despedidas de solteiro.\n\nAcompanho o seu trabalho em {arroba} e queria te propor uma parceria simples: você divulga e ganha comissão de {comissao}% em cada venda que vier de você. Sem meta, sem exclusividade.\n\nSeu público ganha {desconto}% de desconto com o código {codigo} — é só a pessoa falar "venho da parte de {primeiro_nome}" no nosso WhatsApp {nosso_whatsapp}.\n\nTe mando os detalhes do roteiro? Nosso Instagram é {nosso_instagram}.',
    },
    {
      id: 'm2',
      nome: 'Lembrete',
      texto:
        'Oi {primeiro_nome}, tudo certo? Só voltando aqui sobre a parceria com o {crawl}.\n\nSe fizer sentido, já deixo o código {codigo} ativo no seu nome ({desconto}% para o seu público, {comissao}% de comissão para você). Se não for o momento, me avisa que eu te procuro mais para frente — sem problema nenhum.',
    },
    {
      id: 'm3',
      nome: 'Proposta fechada',
      texto:
        '{primeiro_nome}, fechado então. Combinado:\n\n• Código {codigo} — {desconto}% de desconto para quem vier de você\n• Comissão de {comissao}% sobre cada venda com esse código\n• Pagamento por Pix toda semana, com a lista das vendas\n• Você pede: {pedido}\n\nO cliente só precisa falar "venho da parte de {primeiro_nome}, código {codigo}" no WhatsApp {nosso_whatsapp} ou no {nosso_site}.\n\nQualquer ajuste me fala. Abraço, {meu_nome}.',
    },
    {
      id: 'm4',
      nome: 'Turista / despedida',
      texto:
        'Oi {primeiro_nome}! Somos o {crawl}, em {cidade}.\n\nAtendemos muito grupo de despedida de solteiro e turista que chega sem conhecer ninguém — quatro casas, welcome shot em cada uma e anfitrião com o grupo a noite toda.\n\nSe você indicar, seu público entra com {desconto}% usando o código {codigo} e você recebe {comissao}% de comissão. Posso te mandar fotos e o roteiro da semana?',
    },
  ]

  return {
    parceiros,
    vendas,
    clientes,
    sites,
    modelos,
    eu: { nome: 'Eu', instagram: '@nightcrawlsp', whatsapp: '+55 11 90000-0000', site: 'nightcrawl.com.br' },
  }
}
